feat(qr-homepage): implement QR code on homepage
gdsc-hcmut/fessior-fe pull request #15
Opened 2024-01-24 03:45 UTC by anatwork14

2024-01-25 13:21 UTC, lygioian commented on src/components/button/index.tsx
> +  if (image && imageAlt && imageSize) {
if (condition) return <>; 
return <>

Don't use if else for long statement

2024-01-25 13:23 UTC, lygioian commented on src/components/button/index.tsx
> +    );
```suggestion
    return (
      <button disabled={disabled} onClick={onClick} className={buttonClass}>
        {image && imageAlt && imageSize ? <Image
          src={image}
          alt={imageAlt}
          width={imageSize}
          height={imageSize}
          className='pr-1'
        /> : null}
        {children}
      </button>
    );
  } 
```

2024-01-25 13:24 UTC, lygioian commented on src/components/button/index.tsx
> +  imageSize?: number;
imageSize: {width: number; height number;}
or
imageWidth
imageHeight

2024-01-25 13:25 UTC, lygioian commented on src/components/qr-home-button/index.tsx
> +        <Image src={image} alt='icon' height={60} width={60} />
alt='qr-icon'

2024-01-25 13:31 UTC, lygioian commented on src/app/qrcode/website/page.tsx
> +export default function qrWebsite() {
```suggestion
export default function CreateQRURLScreen() {
```

2024-01-25 13:33 UTC, lygioian commented on src/app/qrcode/website/page.tsx
Change folder name website -> qr-url

2024-01-25 13:34 UTC, lygioian commented on src/app/qrcode/page.tsx
> +export default function qrHomePage() {
UPPERCASE on first character of component 
MUST BE QRHomePage
```suggestion
export default function QRHomePage() {
```

2024-01-25 13:35 UTC, lygioian commented on src/app/qrcode/page.tsx
> +          </div>
@dlnanh85 @anatwork14 please move this into one component. It's the same for all screens

2024-01-25 13:36 UTC, lygioian commented on src/app/qrcode/page.tsx
> +      </div>
these code also

2024-01-25 13:37 UTC, lygioian commented on src/app/qrcode/page.tsx
> +'use client';
```suggestion
'use server';
```
this should be 'use server' instead

2024-01-25 13:38 UTC, lygioian commented on src/app/qrcode/page.tsx
> +'use client';
or please remove 'use client', because 'use server' is default

2024-01-25 13:39 UTC, lygioian commented on src/app/qrcode/website/page.tsx
> +        <div className='absolute bottom-[0px] right-[60px] h-[20px] w-[20px] rounded-full bg-primary md:hidden'></div>
like the above comment -> move it to a component

2024-01-25 13:44 UTC, lygioian commented on src/components/text-input/index.tsx
> +    fontSize = 16,
```suggestion
    fontSize = 16,
```
This is a component that combine many other component. fontSize is not clear for us to know what is the fontSize mean in this component. You should change props which belong to input -> inputStyle, props belong to container -> containerStyle it will clear

2024-01-25 14:02 UTC, lygioian commented on package.json
> -    "@types/react": "^18",
please keep version as "^20" why change to fix version ?

2024-01-25 14:07 UTC, dlnanh85 commented on src/components/text-input/index.tsx
> +        height={0}
These props are required for Image component of next/image. However, the documents also suggest using class to specify non-fixed size images, and specify 0 at these props.

2024-03-19 05:26 UTC, dlnanh85 requested changes
- public/icons files must be moved into a smaller folder named 'qr'
- svg file names are inconsistent

2024-03-19 07:02 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +            </p>
If the whole p element is `hidden` in sm view, why would we need <br> with `md:hidden`?

2024-03-19 07:03 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +          {/* <> */}
Remove if not needed

2024-03-19 07:04 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +              image='/icons/link-qr-choosen.svg'
```suggestion
              image='/icons/link-qr-chosen.svg'
```
Grammar of `choosen`

2024-03-19 07:10 UTC, dlnanh85 commented on src/components/button/index.tsx
> +  imageSizeHeight?: number;
The current Button component was designed to accept `children` prop, which is responsible for rendering what will be placed inside a button.
The `children` prop is set as ReactNode, which is literally anything, not just text, but images, icons,... as long as you put all of them inside a big div (as children is a single `ReactNode` not an array of `ReactNode[]`)

In short, this change and all the relevants will not be accepted.

2024-03-19 07:11 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +              <Link href='/qrcode/wifi'>Wi-fi</Link>
`onClick` event handler and Link are doing the same thing

2024-03-19 07:13 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +          <div className='relative mx-auto mb-[172px]  w-[90%] rounded-[8px] border-[3px] border-solid border-primary bg-white p-[16px] shadow-[0px_4px_47px_0px_rgba(11,40,120,0.30)] sm:max-w-[480px]
```suggestion
          <div className='relative mx-auto mb-[172px] w-[90%] rounded-[8px] border-[3px] border-solid border-primary bg-white p-[16px] shadow-[0px_4px_47px_0px_rgba(11,40,120,0.30)] sm:max-w-[480px] md:flex md:w-[85%] md:max-w-[760px] md:flex-grow md:flex-col md:border-[0.5px] md:border-[#7e7e7e4d] lg:w-[100%] lg:max-w-[856px] lg:p-[24px]'>
```
Becareful for typos

2024-03-19 07:14 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +                  iconAlt='icon'
Undescriptive alt text

2024-03-19 07:14 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +                  iconAlt='icon'
Undescriptive alt text

2024-03-19 07:15 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +              domainOptions && ( */}
Remove if not needed

2024-03-19 07:16 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +                  <p className='inline  text-[12px] font-[500] text-black md:text-[16px]'>
typo

2024-03-19 07:17 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +                    dropdownOptions={['GDSC', 'CTCT', 'OISP']}
Having calling APIs at the above useEffect, why hard code the options?

2024-03-19 07:17 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +                    ]}
Why hard-coded?

2024-03-19 07:17 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +              {/* )} */}
Remove if not needed

2024-03-19 07:18 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +                  iconSrc='/icons/search-20px.svg'
What does `20px` mean?

2024-03-19 07:23 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +            </div>
This whole Category input is available on /shorten page. You have 2 options:
1. (More challenging) Extract the available code on /shorten page into a component to reuse it here and /shorten
2. (Easier) Just copy the code on /shorten and paste it right here

2024-03-19 07:30 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +              >
Have a look at the implementation of Button component, with `width === 'full'`, the button is styled with `w-[100%]`.
With that in mind, specifying `width='full'` and classes `w-[136px] md:w-[160px]` right here will result in unexpected behavior of tailwindCSS

2024-03-19 07:35 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +            )} */}
Do you need it?

2024-03-19 07:36 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +      </div>
This part is the same in /src/app/qrcode/qr-wifi
Move all this into /src/app/qrcode/layout.tsx

2024-03-19 07:37 UTC, dlnanh85 commented on src/app/qrcode/qr-wifi/page.tsx
Resolve all mentioned problems in /src/app/qrcode/qr-url/page.tsx for this file.

2024-03-19 07:43 UTC, dlnanh85 commented on src/components/my-url-list/index.tsx
1. Pay attention to VSCode indicators for changes in files you are not supposed to change.
2. DO NOT `git add .` blindly! Inspect carefully which files you are staging.

2024-03-19 07:45 UTC, dlnanh85 commented on src/components/nav/nav-item/index.tsx
Revert this file.

2024-03-19 07:45 UTC, dlnanh85 commented on src/components/nav/user/index.tsx
Unexpected change

2024-03-19 07:47 UTC, dlnanh85 commented on src/components/qr-home-button/index.tsx
> +interface QrHomeButtonProps {
```suggestion
type QrHomeButtonProps = {
```
This is not wrong, but you must follow convention

2024-03-19 07:48 UTC, dlnanh85 commented on src/components/qr-home-button/index.tsx
> +const QrHomeButton = ({ type, image, content }: QrHomeButtonProps) => {
```suggestion
export default function QrHomeButton(props: QrHomeButtonProps) => {
  const { type, image, content } = props;
```
Convention

2024-03-19 07:49 UTC, dlnanh85 commented on src/components/qr-home-button/index.tsx
> +export default QrHomeButton;
```suggestion
```

2024-03-19 07:49 UTC, dlnanh85 commented on src/components/qr-home-button/index.tsx
> +import React from 'react';
```suggestion
```

2024-03-19 07:49 UTC, dlnanh85 commented on src/components/qr-home-button/index.tsx
This component was not used anywhere in the project?

2024-03-19 07:51 UTC, dlnanh85 commented on src/components/qr-navbar/index.tsx
> +'use client';
Only `use client` wherever you need to use React's hooks (useState, useEffect,...)

2024-03-19 07:51 UTC, dlnanh85 commented on src/components/qr-navbar/index.tsx
This component was also not used anywhere in the project.

2024-03-19 07:53 UTC, dlnanh85 commented on yarn.lock
This file should not be changed without `package.json`, revert this file.

2024-03-22 04:01 UTC, dlnanh85 requested changes

2024-03-27 15:03 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +  };
```suggestion
  const logUrlInfo = () => {
    const UrlInfo = {
      inputQRName,
      inputURL,
      organizationValue,
      domainValue,
      categoryValues,
    };
    console.log(UrlInfo);
  };
```

2024-03-27 15:36 UTC, dlnanh85 requested changes

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +  };
```suggestion
  const logUrlInfo = () => {
    const urlInfo = {
      inputQRName,
      inputURL,
      organizationValue,
      domainValue,
      categoryValues,
    };
    console.log(urlInfo);
  };
```

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +  const [errorMessage, setErrorMessage] = useState('');
Unused variable

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/qr-url/page.tsx
> +        )}
![image](https://github.com/gdsc-hcmut/fessior-fe/assets/69638256/0a36af6d-3b47-468d-8835-e60562b5ff81)
Domain is too close from Category input

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/qr-wifi/page.tsx
![image](https://github.com/gdsc-hcmut/fessior-fe/assets/69638256/b8aa7cde-b925-4b77-a2a3-084a24661a3f)
![image](https://github.com/gdsc-hcmut/fessior-fe/assets/69638256/a1f4e081-1ecc-4871-90a1-53d2a0f4d8d4)
Organization font-size is uneven

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/qr-wifi/page.tsx
> +            </button>
```suggestion
            <Input
              fontSize={inputFontSize}
              type={passwordVisible ? 'text' : 'password'}
              iconSrc='/icons/qrcode/password.svg'
              iconAlt='password-icon'
              placeholder='Enter your password'
              textValue={inputPassword}
              divider={true}
              onInput={setInputPassword}
              height={inputHeight}
              onEnter={() => {
                logWifiInfo();
              }}
              className='pr-8'
            />
```
The Input component is supposed to support both left and right icon.
-> Remove the button for show/hide password, accept this as a bug that will be fixed in later PRs (by modifying the Input component to accept multiple icons)

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/qr-wifi/page.tsx
> +            </div>
![image](https://github.com/gdsc-hcmut/fessior-fe/assets/69638256/a384e1a2-ea9d-4b13-b267-561e7421809d)
Uneven width

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/qr-wifi/page.tsx
> +  };
```suggestion
  const logWifiInfo = () => {
    const wifiInfo = {
      inputQRName,
      inputSSID,
      inputPassword,
      inputEncryption,
      organizationValue,
      categoryValues,
    };
    console.log(wifiInfo);
  };
```

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/qr-wifi/page.tsx
![image](https://github.com/gdsc-hcmut/fessior-fe/assets/69638256/6eac86db-5f3e-48a0-9291-82852faeffac)
Bug

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/layout.tsx
> +  }, [currentPathname]);
For such difference, it's better to use `template` than `layout`, but this is fine, for now.

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/layout.tsx
> +                // logUrlInfo();
Remove if not used

2024-03-27 15:36 UTC, dlnanh85 commented on src/app/qrcode/layout.tsx
> +                // logUrlInfo();
Remove if not used

2024-03-28 12:40 UTC, dlnanh85 submitted a review, later dismissed

2024-03-31 07:30 UTC, Jamesklein218 requested changes
Refer to Khánh's PR (pr 22). Add padding to match with the header and footer.

2024-03-31 07:30 UTC, Jamesklein218 commented on src/app/qrcode/qr-url/page.tsx
> +              categoryValues!.filter(
Consider using optional chaining `?.`. Reference: https://stackoverflow.com/a/65802349/21080445. Moreover, when code you should like of edge cases: if `categoryValues` is undefined -> `setCategoryValues(undefined)`. Should provide a fallback value. My recommendation is to change this line into:

```
            setCategoryValues(
              categoryValues?.filter(
                (categoryValue) => categoryValue._id !== category._id,
              ) || []
            );
```

Fix this for other values below

2024-03-31 07:30 UTC, Jamesklein218 commented on src/app/qrcode/qr-url/page.tsx
> +      <div className='relative mx-auto mb-[172px] w-[90%] rounded-[8px] border-[3px] border-solid border-primary bg-white p-[16px] shadow-[0px_4px_47px_0px_rgba(11,40,120,0.30)] sm:max-w-[480px] md:f
Too long of a line. Usually eslint should check for code < 100 characters.

2024-03-31 07:30 UTC, Jamesklein218 commented on src/app/qrcode/qr-url/page.tsx
> +  const isLoaded =
`useMemo` should be used here

2024-03-31 07:30 UTC, Jamesklein218 commented on src/app/qrcode/qr-url/page.tsx
> +                  handleChange(ShortenInputFieldEnum.ORGANIZATION) as (
Why do we need to use add here ? You can change the parameter of `handleChange` to `value`. Please note that we want to has less `any` and `as` in the Typescript environment.

2024-03-31 07:30 UTC, Jamesklein218 commented on src/app/qrcode/qr-url/page.tsx
> +      const message = e.response.data.message;
Check if `e.response.data.message` is null-ish. Also use optional chaining '?.' here to prevent error.

2024-03-31 07:30 UTC, Jamesklein218 commented on src/app/qrcode/qr-wifi/page.tsx
I commented the other `qr-url` page, this file should be changed accordingly.

2024-03-31 07:30 UTC, Jamesklein218 commented on src/app/qrcode/qr-wifi/page.tsx
> +  const [inputEncryption, setInputEncryption] = useState('WPA/WPA2');
Enum should be used here, create a local enum like `EncryptionType` that contains values: ['WPA/WPA2', 'WEP', 'NONE', 'RAW']

2024-03-31 07:30 UTC, Jamesklein218 commented on src/app/qrcode/qr-wifi/page.tsx
> +        urls: [] as Url['_id'][],
I see the `Url['_id']` is basically a string. should this just be `string[]` ?

2024-04-08 14:23 UTC, NooBat approved these changes
LGTM!

2024-04-08 14:23 UTC, merged