Feature/qr customize page
gdsc-hcmut/fessior-fe pull request #22
Opened 2024-01-31 15:33 UTC by kahn-29

- Information's part and Frame's part.
- Tablet size and Mobile size are available.

2024-03-31 05:55 UTC, dlnanh85 requested changes

2024-03-31 05:55 UTC, dlnanh85 commented on src/components/qr-information/index.tsx
> +import iconTag from '@/../public/icons/qr/iconTag.svg';
```suggestion
```
Assets files does not need to be imported. Fix other files too.

2024-03-31 05:55 UTC, dlnanh85 commented on src/components/qr-miniPreview/index.tsx
Folder name (kebab-case) and Component's name (PascalCase) must be the same

2024-03-31 06:24 UTC, Jamesklein218 requested changes
![sd](https://github.com/gdsc-hcmut/fessior-fe/assets/26504967/ab548131-a5eb-47f1-a666-e2fe4fc046fc)
For the style of the page, I think you should align with the header and footer (please refer to the image above)

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/qr-frame/index.tsx
Why is there so much module specific components: `qr-logo`, `qr-miniPreview`, `qr-navbar`, etc. When create a component, we should ask "Is this component reusable?". If not, we shouldn't create one. If yes, should this be a pure component (button, radio selector, etc., usually the component of the web's design system) or a module specifc components. Please review all these components, or move them to a `qr` directory in the `components` directory.

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/qr-information/index.tsx
> +type props = { typeOfQR: string };
`type InformationPartProps`

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/qr-information/index.tsx
> +          <svg
Should this svg here be defined inline? Should it be in public ?

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/qr-information/index.tsx
> +          <svg
Same with this svg, please move all to the `public` directory

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/qr-frame/index.tsx
One more thing to note, components are most likely to depend on a set of props (because they are reusable). I observe that most new component here does not. Please rewrite.

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/qr-pattern/index.tsx
> +  const [patternColorType, setPatternColorType] = useState('singleColor');
As comment above, we should define an enum (globally or locally) here. Such as `enum PatternColorType = 'singleColor' | ...`.

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/qr-pattern/index.tsx
> +  const [dotsType, setDotsType] = useState<DotType>('square');
Optionally but I think DotType is an enum, therefore, I think this line should be `  const [dotsType, setDotsType] = useState<DotType>(DotType.Square);` or somethign similar. Small change.

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/qr-pattern/index.tsx
> +
Should eslint catch this styling error ? Remove these empty lines

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/toggle-button/index.tsx
> +const ToggleButton: React.FC<ToggleButtonProps> = ({ type }) => {
Eslint should also catch this error. The function here does not have a default return value (shouldn't be `undefined` but `null` for a React component. If type == 'laptop', React may throw error.

2024-03-31 06:24 UTC, Jamesklein218 commented on src/components/toggle-button/index.tsx
> +  if (type === 'mobile') {
Should this be an `if` `else`? I observe the different between type mobile and tablet is in classname. I think you should use `clsx`.

2024-03-31 06:31 UTC, kahn-29 commented on package-lock.json
Thank for your review, I have deleted this file.

2024-03-31 06:32 UTC, kahn-29 commented on package.json
> +    "typescript": "5.3.3"
Thank for your review, I have revert these change.

2024-03-31 06:37 UTC, kahn-29 commented on .vscode/settings.json
Thank for your review, I have deleted this file.

2024-03-31 06:39 UTC, kahn-29 commented on public/icons/qr/iconFacebook.svg
Thanks for your feedback. I've renamed all the files in the 'public/icons/qr' folder to follow the correct naming convention.

2024-03-31 09:15 UTC, kahn-29 commented on src/components/qr-pattern/index.tsx
> +  const [dotsType, setDotsType] = useState<DotType>('square');
DotType is belonging to the qr-code-styling' library.
`export declare type DotType = "dots" | "rounded" | "classy" | "classy-rounded" | "square" | "extra-rounded";`
So I think current version is fine.

2024-03-31 09:24 UTC, kahn-29 commented on src/components/qr-pattern/index.tsx
> +  const [dotsType, setDotsType] = useState<DotType>('square');
![Screenshot 2024-03-31 162248](https://github.com/gdsc-hcmut/fessior-fe/assets/147742942/36623244-0043-4e08-ab70-270ef106d179)

2024-03-31 09:26 UTC, Jamesklein218 commented on src/components/qr-pattern/index.tsx
> +  const [dotsType, setDotsType] = useState<DotType>('square');
Then I'm wrong here, check what type is DotType, if it is a string such as `type DotType = 'abc' | 'xyz'`, then your implementation is correct.

2024-04-09 14:13 UTC, NooBat approved these changes
LGTM!

2024-04-09 14:14 UTC, merged