Origin/feat/my url page
gdsc-hcmut/fessior-fe pull request #23
Opened 2024-02-17 11:49 UTC by Mdtr3002

Create UI for the "My URL" page

2024-02-20 03:28 UTC, tomgermanyyyy requested changes

2024-02-22 04:24 UTC, Mdtr3002 commented on src/app/urls/page.tsx
> +  const sortOption = ['Latest', 'Oldest', 'Most Clicked', 'Least Clicked'];
Em có tạo rồi nha anh

2024-02-22 04:24 UTC, Mdtr3002 commented on src/app/urls/page.tsx
> +  const swithSortOption = (option: string) => {
Em có chỉnh lại rồi:)

2024-02-22 04:24 UTC, Mdtr3002 commented on src/components/button/url-button/index.tsx
> +}
Em chỉnh lại rồi nha a

2024-02-22 08:03 UTC, merged