feat(admin): add/edit organization modal
gdsc-hcmut/fessior-fe pull request #68
Opened 2024-05-12 09:09 UTC by dlnanh85

2024-06-02 14:23 UTC, NooBat reviewed
I realized something for every files, we sometimes use alias imports (`@`), and sometimes we not. Can we make every import an alias imports?

2024-06-02 14:28 UTC, NooBat requested changes

2024-06-02 14:28 UTC, NooBat commented on src/app/admin/organizations/components/OrganizationModal/OrganizationForm.tsx
> +    const isManager = useCallback(
Please remove `useCallback` and `useMemo` used in this component since `organizationDetails` changes on every input so I think memoization is meaningless.

2024-06-02 14:28 UTC, NooBat commented on src/app/admin/organizations/components/OrganizationModal/OrganizationForm.tsx
> +          {nonMemberUsers && (
Can we stop using short circuit for this? Please use ternary operator `? :` instead.

2024-06-02 14:28 UTC, NooBat commented on src/app/admin/src/utils/common.ts
> +  const hash: { [key in string]: number } = {};
I think you should just use `Set` in javascript, input them all in a `Set` then turn that `Set` into an array.

2024-06-03 13:09 UTC, dlnanh85 commented on src/app/admin/organizations/components/OrganizationModal/BaseOrganizationModal.tsx
> +  const handleSaveButtonClick = useCallback(() => {
The `organizationDetails` has multiple fields, which indeed make it changes in every render. But that's also the reason I specified `organizationDetails.longName` for the deps instead of the whole object. Would that make any differences?

So I think the the function will still be worth memoized as long as the `longName` is the same while the other fields are changing.

Please let me know if I understand something wrong. TYSM.

2024-06-03 13:12 UTC, dlnanh85 commented on src/app/admin/organizations/components/OrganizationModal/OrganizationForm.tsx
> +    const isManager = useCallback(
It's the same case as above, but I made a mistake here by setting the deps as the whole object, I will change these whole object to track its properties only.

I find these array operations quite expensive, and worth memoizing.

2024-06-03 16:20 UTC, dlnanh85 commented
About the alias imports, I will have a PR to update this convention later.
@NooBat

2024-06-11 17:25 UTC, NooBat commented on src/app/admin/organizations/components/OrganizationModal/OrganizationForm.tsx
> +    const isManager = useCallback(
I think you haven't fixed this yet

2024-06-11 17:31 UTC, NooBat commented on src/app/admin/organizations/page.tsx
> +        setOrganizations(organizations?.concat(newOrganization) ?? null);
I think that instead of using the state, you can use `setOrganizations((prevState) => prevState.concat(...))`

2024-06-11 17:35 UTC, dlnanh85 commented on src/app/admin/organizations/components/OrganizationModal/OrganizationForm.tsx
> +    const isManager = useCallback(
I believe I did, I changed the `organizationDetails` to specifically track its property `organizationDetails.manager` (line 28) and `organizationDetails.member` (line 33, 38).

Please check if you are viewing this file from the most recent commit. 
Cheers.

2024-06-12 15:16 UTC, NooBat approved these changes

2024-06-12 15:23 UTC, merged